apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-appsettings
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Error",
          "Microsoft": "Error",
          "Microsoft.Hosting.Lifetime": "Error"
        }
      }
    }