apiVersion: v1
kind: Pod
metadata:
  name: curl
spec:
  containers:
    - name: curl
      image: "radial/busyboxplus:curl"      
      command:
        - sleep
        - "3600"
  restartPolicy: Always
